require_relative '../lib/wordgenerator.rb'
require_relative '../lib/hangman.rb'
require_relative '../lib/phrase.rb'
require_relative '../lib/display.rb'
require_relative '../views/pickletters.rb'
require_relative '../controllers/application_controller.rb'
require_relative '../lib/HangmanCLI.rb'
